hmrc/hmrc-email-renderer

app/preview/TemplateParams.scala
app/uk/gov/hmrc/hmrcemailrenderer/templates/mandate/MandateTemplates.scala
app/uk/gov/hmrc/hmrcemailrenderer/templates/mandate/mandateAgentRemoves.scala.html
app/uk/gov/hmrc/hmrcemailrenderer/templates/mandate/mandateAgentRemoves.scala.txt
app/uk/gov/hmrc/hmrcemailrenderer/templates/mandate/mandateClientCancelsActive.scala.html
app/uk/gov/hmrc/hmrcemailrenderer/templates/mandate/mandateClientCancelsActive.scala.txt
test/uk/gov/hmrc/hmrcemailrenderer/templates/TemplateLocatorSpec.scala

- added "client_cancels_active_mandate" mandate template
- updated text in "agent_removes_mandate" template

added new mandate template, updated existing template

---

app/preview/TemplateParams.scala
app/uk/gov/hmrc/hmrcemailrenderer/templates/ServiceIdentifier.scala
app/uk/gov/hmrc/hmrcemailrenderer/templates/TemplateLocator.scala
app/uk/gov/hmrc/hmrcemailrenderer/templates/gg/GgTemplates.scala
app/uk/gov/hmrc/hmrcemailrenderer/templates/gg/ggUserIdNotificationEmail.scala.html
app/uk/gov/hmrc/hmrcemailrenderer/templates/gg/ggUserIdNotificationEmail.scala.txt
test/uk/gov/hmrc/hmrcemailrenderer/templates/TemplateLocatorSpec.scala

https://jira.tools.tax.service.gov.uk/browse/DC-777
https://jira.tools.tax.service.gov.uk/browse/GG-1772

GG-1772 [GC,AH] Added userid notification email template

---

app/preview/TemplateParams.scala
app/uk/gov/hmrc/hmrcemailrenderer/templates/customs/CustomsTemplates.scala
app/uk/gov/hmrc/hmrcemailrenderer/templates/customs/customsRegistrationNotSuccessful.scala.html
app/uk/gov/hmrc/hmrcemailrenderer/templates/customs/customsRegistrationNotSuccessful.scala.txt
app/uk/gov/hmrc/hmrcemailrenderer/templates/customs/customsRegistrationSuccessful.scala.html
app/uk/gov/hmrc/hmrcemailrenderer/templates/customs/customsRegistrationSuccessful.scala.txt
test/uk/gov/hmrc/hmrcemailrenderer/templates/TemplateLocatorSpec.scala
test/uk/gov/hmrc/hmrcemailrenderer/templates/customs/CustomsTemplatesContentComparisonSpec.scala
test/uk/gov/hmrc/hmrcemailrenderer/templates/digitalcontact/TemplateContentComparisonSpec.scala

The user needs to be informed about a subscription completion, either for a success or failure.
2 email templates to communicate this to the user.

CDD-792: 2 emails about a customs services subscription completion

---

app/preview/TemplateParams.scala
app/uk/gov/hmrc/hmrcemailrenderer/templates/ServiceIdentifier.scala
app/uk/gov/hmrc/hmrcemailrenderer/templates/TemplateLocator.scala
app/uk/gov/hmrc/hmrcemailrenderer/templates/emachelpdesk/EmacHelpdeskTemplates.scala
app/uk/gov/hmrc/hmrcemailrenderer/templates/emachelpdesk/emacHelpdeskFailureConfirmationEmail.scala.html
app/uk/gov/hmrc/hmrcemailrenderer/templates/emachelpdesk/emacHelpdeskFailureConfirmationEmail.scala.txt
app/uk/gov/hmrc/hmrcemailrenderer/templates/emachelpdesk/emacHelpdeskSuccessfulConfirmationEmail.scala.html
app/uk/gov/hmrc/hmrcemailrenderer/templates/emachelpdesk/emacHelpdeskSuccessfulConfirmationEmail.scala.txt
it/uk/gov/hmrc/hmrcemailrenderer/TemplatePrioritiesISpec.scala
test/uk/gov/hmrc/hmrcemailrenderer/templates/TemplateLocatorSpec.scala

added EMAC Helpdesk templates

---

app/uk/gov/hmrc/hmrcemailrenderer/templates/api/verificationEmail.scala.html
app/uk/gov/hmrc/hmrcemailrenderer/templates/api/verificationEmail.scala.txt
test/uk/gov/hmrc/hmrcemailrenderer/templates/api/ApiVerficationEmailSpec.scala

Reverts hmrc/hmrc-email-renderer#86
Re-merging the original PR as there is a fix in a separate PR.

Revert "Revert "Apis-878 - Edit content of verification email""

---

app/preview/TemplateParams.scala
app/uk/gov/hmrc/hmrcemailrenderer/templates/ServiceIdentifier.scala
app/uk/gov/hmrc/hmrcemailrenderer/templates/TemplateLocator.scala
app/uk/gov/hmrc/hmrcemailrenderer/templates/dfs/DfsTemplates.scala
app/uk/gov/hmrc/hmrcemailrenderer/templates/lisa/LisaTemplates.scala
app/uk/gov/hmrc/hmrcemailrenderer/templates/lisa/applicationSubmitted.scala.html
app/uk/gov/hmrc/hmrcemailrenderer/templates/lisa/applicationSubmitted.scala.txt
test/uk/gov/hmrc/hmrcemailrenderer/templates/TemplateLocatorSpec.scala

Created the email template for the LISA application submission.

Lisa application  submitted email template

---

app/preview/TemplateParams.scala
app/uk/gov/hmrc/hmrcemailrenderer/templates/ServiceIdentifier.scala
app/uk/gov/hmrc/hmrcemailrenderer/templates/TemplateLocator.scala
app/uk/gov/hmrc/hmrcemailrenderer/templates/eeitt/EeittTemplates.scala
app/uk/gov/hmrc/hmrcemailrenderer/templates/eeitt/eeittSubmissionConfirmation.scala.html
app/uk/gov/hmrc/hmrcemailrenderer/templates/eeitt/eeittSubmissionConfirmation.scala.txt
test/uk/gov/hmrc/hmrcemailrenderer/templates/TemplateLocatorSpec.scala

Adding the initial eeitt confirmation email

Eeitt test template

---

app/preview/TemplateParams.scala
app/uk/gov/hmrc/hmrcemailrenderer/templates/onlinepaymentservice/OnlinePaymentServiceTemplates.scala
app/uk/gov/hmrc/hmrcemailrenderer/templates/onlinepaymentservice/payment_successful_cy.scala.html
app/uk/gov/hmrc/hmrcemailrenderer/templates/onlinepaymentservice/payment_successful_cy.scala.txt
test/uk/gov/hmrc/hmrcemailrenderer/templates/TemplateLocatorSpec.scala

Adding translated version of email for HMRC Payment Confirmation.

OPS-1103 adding Welsh version of payment_successful

---

app/preview/TemplateParams.scala
app/uk/gov/hmrc/hmrcemailrenderer/templates/fhdds/FhddsTemplates.scala
app/uk/gov/hmrc/hmrcemailrenderer/templates/fhdds/fhddsBetaSubmissionWithdrawal.scala.html
app/uk/gov/hmrc/hmrcemailrenderer/templates/fhdds/fhddsBetaSubmissionWithdrawal.scala.txt
test/uk/gov/hmrc/hmrcemailrenderer/templates/TemplateLocatorSpec.scala

added necessary config for tests

Fhdds 1028 withdrawals

---

app/uk/gov/hmrc/hmrcemailrenderer/templates/lisa/applicationSubmitted.scala.html
app/uk/gov/hmrc/hmrcemailrenderer/templates/lisa/applicationSubmitted.scala.txt

Added clarification that the 14 day review process is 14 calendar days, as per latest content review.

LISA-1883: Updated LISA application submitted emails

---

app/uk/gov/hmrc/hmrcemailrenderer/templates/amls/amlsNotificationReceived.scala.html
app/uk/gov/hmrc/hmrcemailrenderer/templates/amls/amlsNotificationReceived.scala.txt

Changed content on notification received html/txt files to allow users to have a clearer understanding of where to go.

Amls template change

---

app/uk/gov/hmrc/hmrcemailrenderer/templates/hts/htsEmailVerification.scala.html

Swap out straight quotes for smart quotes.

Add smartquotes to hts email verification

---

app/uk/gov/hmrc/hmrcemailrenderer/templates/fhdds/FhddsTemplates.scala

Set message priority to urgent for verifications emails.

FHDDS-1267: set message priority for verifications to urgent

---

app/uk/gov/hmrc/hmrcemailrenderer/templates/eeitt/EeittTemplates.scala
app/uk/gov/hmrc/hmrcemailrenderer/templates/eeitt/bd510ReturnConfirmation.scala.html
app/uk/gov/hmrc/hmrcemailrenderer/templates/eeitt/bd510ReturnConfirmation.scala.txt
test/uk/gov/hmrc/hmrcemailrenderer/templates/TemplateLocatorSpec.scala

Bingo Duty email template

---

app/uk/gov/hmrc/hmrcemailrenderer/templates/eeitt/EeittTemplates.scala
app/uk/gov/hmrc/hmrcemailrenderer/templates/eeitt/ltRegConfirmation.scala.html
app/uk/gov/hmrc/hmrcemailrenderer/templates/eeitt/ltRegConfirmation.scala.txt
app/uk/gov/hmrc/hmrcemailrenderer/templates/eeitt/researchAndDevelopmentSubmission.scala.html
app/uk/gov/hmrc/hmrcemailrenderer/templates/eeitt/researchAndDevelopmentSubmission.scala.txt

Email rand d

---

app/preview/TemplateParams.scala
app/uk/gov/hmrc/hmrcemailrenderer/templates/ServiceIdentifier.scala
app/uk/gov/hmrc/hmrcemailrenderer/templates/digitaltariffs/DigitalTariffTemplates.scala
app/uk/gov/hmrc/hmrcemailrenderer/templates/digitaltariffs/adviceRequest.scala.html
app/uk/gov/hmrc/hmrcemailrenderer/templates/digitaltariffs/adviceRequest.scala.txt
test/uk/gov/hmrc/hmrcemailrenderer/templates/TemplateLocatorSpec.scala

This adds an "Advice Request" Email **which will only ever be sent to the HMRC Classification Team**

DIT-69 Digital Tariffs Advice Request Template

---

app/uk/gov/hmrc/hmrcemailrenderer/templates/digitalcontact/DigitalContactTemplates.scala
app/uk/gov/hmrc/hmrcemailrenderer/templates/digitalcontact/rescindedMessageAlert.scala.html
app/uk/gov/hmrc/hmrcemailrenderer/templates/digitalcontact/rescindedMessageAlert.scala.txt

[DC-1764] Rescindment for SA316 sent on 19/02/2019

---

app/preview/TemplateParams.scala
app/uk/gov/hmrc/hmrcemailrenderer/templates/twowaymessage/twoWayMessageNotificationTemplate.scala.html
app/uk/gov/hmrc/hmrcemailrenderer/templates/twowaymessage/twoWayMessageNotificationTemplate.scala.txt
app/uk/gov/hmrc/hmrcemailrenderer/templates/twowaymessage/twoWayMessageRecievedTemplate.scala.html
app/uk/gov/hmrc/hmrcemailrenderer/templates/twowaymessage/twoWayMessageRecievedTemplate.scala.txt
app/uk/gov/hmrc/hmrcemailrenderer/templates/twowaymessage/twoWayMessagingTemplates.scala

Includes response time text update too.

DC-1816-name-in-2wm-email

---

app/uk/gov/hmrc/hmrcemailrenderer/templates/parcels/parcelsRegistered.scala.txt

Changing to 'Manage your import VAT on parcels'

Updated text in parcels email

---

app/preview/TemplateParams.scala
app/uk/gov/hmrc/hmrcemailrenderer/templates/onlinepaymentservice/OnlinePaymentServiceTemplates.scala
app/uk/gov/hmrc/hmrcemailrenderer/templates/onlinepaymentservice/payment_successful_parcels.scala.html
app/uk/gov/hmrc/hmrcemailrenderer/templates/onlinepaymentservice/payment_successful_parcels.scala.txt
test/uk/gov/hmrc/hmrcemailrenderer/templates/TemplateLocatorSpec.scala

final changes to make email match up

Edtaylor/ops 2268/custom email for parcels card payment success

---

app/preview/TemplateParams.scala
app/uk/gov/hmrc/hmrcemailrenderer/templates/onlinepaymentservice/payment_successful_parcels.scala.html
app/uk/gov/hmrc/hmrcemailrenderer/templates/onlinepaymentservice/payment_successful_parcels.scala.txt

Made the changes that where requested for in ticket https://jira.tools.tax.service.gov.uk/browse/OPS-2268

[SM][OPS-2268]

---

CONTRIBUTING.md
app/uk/gov/hmrc/hmrcemailrenderer/templates/customsfinancials/CustomsFinancialsTemplates.scala
app/uk/gov/hmrc/hmrcemailrenderer/templates/customsfinancials/ImportAdjustmentEmail.scala.html
app/uk/gov/hmrc/hmrcemailrenderer/templates/customsfinancials/postponedImportVATStatement.scala.html
app/uk/gov/hmrc/hmrcemailrenderer/templates/customsfinancials/postponedImportVATStatement.scala.txt
test/uk/gov/hmrc/hmrcemailrenderer/templates/TemplateLocatorSpec.scala
test/uk/gov/hmrc/hmrcemailrenderer/templates/customsFinancials/CustomsFinancialsSpec.scala

Can this merged please. This is a part of MMCA-1692

Postponed VAT email templates.

---

app/preview/TemplateParams.scala
app/uk/gov/hmrc/hmrcemailrenderer/templates/tdq/TdqTemplates.scala
app/uk/gov/hmrc/hmrcemailrenderer/templates/tdq/extraparams/ValidConnectionMethodBase64EncodedDetails.scala
app/uk/gov/hmrc/hmrcemailrenderer/templates/tdq/tdqHeaderCompliancePartiallyCompliantInvalidOrMissingConnectionMethod.scala.html
app/uk/gov/hmrc/hmrcemailrenderer/templates/tdq/tdqHeaderCompliancePartiallyCompliantInvalidOrMissingConnectionMethod.scala.txt
app/uk/gov/hmrc/hmrcemailrenderer/templates/tdq/tdqHeaderCompliancePartiallyCompliantValidConnectionMethod.scala.html
app/uk/gov/hmrc/hmrcemailrenderer/templates/tdq/tdqHeaderCompliancePartiallyCompliantValidConnectionMethod.scala.txt
test/uk/gov/hmrc/hmrcemailrenderer/templates/TemplateLocatorSpec.scala
test/uk/gov/hmrc/hmrcemailrenderer/templates/tdq/TdqTemplatesSpec.scala
test/uk/gov/hmrc/hmrcemailrenderer/templates/tdq/ValidConnectionMethodBase64EncodedDetailsSpec.scala

Adds two emails templates for TDQ partially compliant emails

TDQ-635: Partially compliant templates

---

app/preview/TemplateParams.scala
app/uk/gov/hmrc/hmrcemailrenderer/templates/TemplateLocator.scala
app/uk/gov/hmrc/hmrcemailrenderer/templates/ats/AtsTemplates.scala
app/uk/gov/hmrc/hmrcemailrenderer/templates/ats/annualTaxSummariesMessageAlert_cy.scala.html
app/uk/gov/hmrc/hmrcemailrenderer/templates/ats/annualTaxSummariesMessageAlert_cy.scala.txt
app/uk/gov/hmrc/hmrcemailrenderer/templates/digitalcontact/DigitalContactTemplates.scala
app/uk/gov/hmrc/hmrcemailrenderer/templates/digitalcontact/newMessageAlert_cy.scala.html
app/uk/gov/hmrc/hmrcemailrenderer/templates/digitalcontact/newMessageAlert_cy.scala.txt
app/uk/gov/hmrc/hmrcemailrenderer/templates/digitalcontact/rescindedMessageAlert_cy.scala.html
app/uk/gov/hmrc/hmrcemailrenderer/templates/digitalcontact/rescindedMessageAlert_cy.scala.txt
app/uk/gov/hmrc/hmrcemailrenderer/templates/digitalcontact/verificationReminder_cy.scala.html
app/uk/gov/hmrc/hmrcemailrenderer/templates/digitalcontact/verificationReminder_cy.scala.txt
app/uk/gov/hmrc/hmrcemailrenderer/templates/helpers/SalutationHelper.scala
app/uk/gov/hmrc/hmrcemailrenderer/templates/helpers/salutation.scala.html
app/uk/gov/hmrc/hmrcemailrenderer/templates/helpers/salutation.scala.txt
app/uk/gov/hmrc/hmrcemailrenderer/templates/helpers/template_footer_cy.scala.txt
app/uk/gov/hmrc/hmrcemailrenderer/templates/helpers/template_main.scala.html
app/uk/gov/hmrc/hmrcemailrenderer/templates/paye/PayeTemplates.scala
app/uk/gov/hmrc/hmrcemailrenderer/templates/paye/taxEstimateMessageAlert_cy.scala.html
app/uk/gov/hmrc/hmrcemailrenderer/templates/paye/taxEstimateMessageAlert_cy.scala.txt
project/build.properties
test/uk/gov/hmrc/hmrcemailrenderer/templates/AtsTemplates/AtsAnnualTaxReturnWelshSpec.scala
test/uk/gov/hmrc/hmrcemailrenderer/templates/RenderedEmailSpec.scala
test/uk/gov/hmrc/hmrcemailrenderer/templates/TemplateLocatorSpec.scala
test/uk/gov/hmrc/hmrcemailrenderer/templates/digitalcontact/NewMessageAlertWelshSpec.scala
test/uk/gov/hmrc/hmrcemailrenderer/templates/digitalcontact/RescindedMessageAlertWelshSpec.scala
test/uk/gov/hmrc/hmrcemailrenderer/templates/digitalcontact/VerificationReminderWelshSpec.scala
test/uk/gov/hmrc/hmrcemailrenderer/templates/helpers/SalutationHelperSpec.scala
test/uk/gov/hmrc/hmrcemailrenderer/templates/paye/TaxEstimateMessageAlertWelshSpec.scala

- rescindedMessageAlert_cy
- verificationReminder_cy
- tax_estimate_message_alert_cy
- annual_tax_summaries_message_alert_cy
- newMessageAlert_cy

DC-2251: Add Welsh templates

---

app/uk/gov/hmrc/hmrcemailrenderer/templates/htsreminder/htsReminderEmail.scala.html
app/uk/gov/hmrc/hmrcemailrenderer/templates/htsreminder/htsReminderEmail.scala.txt

DLS-2087 Dynamic date corrected

DLS-2087 Dynamic date corrected

---

app/uk/gov/hmrc/hmrcemailrenderer/templates/digitalcontact/verificationReminder.scala.html
app/uk/gov/hmrc/hmrcemailrenderer/templates/digitalcontact/verificationReminder.scala.txt
app/uk/gov/hmrc/hmrcemailrenderer/templates/digitalcontact/verificationReminder_cy.scala.html
app/uk/gov/hmrc/hmrcemailrenderer/templates/digitalcontact/verificationReminder_cy.scala.txt
project/MicroServiceBuild.scala
project/plugins.sbt
test/uk/gov/hmrc/hmrcemailrenderer/templates/digitalcontact/TemplateContentComparisonSpec.scala
test/uk/gov/hmrc/hmrcemailrenderer/templates/digitalcontact/VerificationReminderWelshSpec.scala

This reverts commit 9d0d08b9742131d8810b41b76e3c9cc24e58d1dc.

Revert "DC-2285: verification reminder must have link"

---

app/preview/TemplateParams.scala
app/uk/gov/hmrc/hmrcemailrenderer/templates/htsreminder/htsReminderEmail.scala.html
app/uk/gov/hmrc/hmrcemailrenderer/templates/htsreminder/htsReminderEmail.scala.txt

DC-2405 Month name dynamically supplied

DC-2405 Month name dynamically supplied

---

app/uk/gov/hmrc/hmrcemailrenderer/templates/onlinepaymentservice/ddi_cancelled_dcs_alert.scala.html
app/uk/gov/hmrc/hmrcemailrenderer/templates/onlinepaymentservice/ddi_cancelled_dcs_alert.scala.txt
app/uk/gov/hmrc/hmrcemailrenderer/templates/onlinepaymentservice/ddi_unpaid_dcs_alert.scala.html
app/uk/gov/hmrc/hmrcemailrenderer/templates/onlinepaymentservice/ddi_unpaid_dcs_alert.scala.txt

Revert "[AJN][OPS-4647][DC-2466] Remove content about paying by another method from DD emails (#485)"
This reverts commit ed82f1534043c424ebaf91c240afbd64934242a3.

[JR][OPS-4969][DC-2629] Revert email nudge VAT DD changes for Covid 19.

---

app/uk/gov/hmrc/hmrcemailrenderer/templates/digitaltariffs/DigitalTariffTemplates.scala
app/uk/gov/hmrc/hmrcemailrenderer/templates/digitaltariffs/applicationSubmitted.scala.html
app/uk/gov/hmrc/hmrcemailrenderer/templates/digitaltariffs/applicationSubmitted.scala.txt

changed content for "check status of application" in digitaltariffs->applicationSubmitted

DIT-2371 # digital-tariffs: changed content for "check status of application" 

---

app/uk/gov/hmrc/hmrcemailrenderer/templates/digitaltariffs/applicationSubmitted.scala.html
app/uk/gov/hmrc/hmrcemailrenderer/templates/digitaltariffs/applicationSubmitted.scala.txt

corrected Advanced -> Advance for digital tariffs applicationSubmitted template.

DC-2795 and DIT-2371 # minor correction

---

app/uk/gov/hmrc/hmrcemailrenderer/connectors/PreferencesConnector.scala
test/uk/gov/hmrc/hmrcemailrenderer/connectors/PreferencesConnectorSpec.scala

This reverts commit 6deecad9076a8bbf3b060caa589fd7ecdee3c9da.

Revert "[DC-2785] use encrypted email in preference connector (#631)"

---

app/preview/TemplateParams.scala
app/uk/gov/hmrc/hmrcemailrenderer/templates/onlinepaymentservice/passengers_confirmation.scala.html
app/uk/gov/hmrc/hmrcemailrenderer/templates/onlinepaymentservice/passengers_confirmation.scala.txt

PAS-1122: Passengers email template changes
PR link for bc-passengers-declarations: https://github.com/hmrc/bc-passengers-declarations/pull/55

PAS-1122: Passengers email template changes

---

app/uk/gov/hmrc/hmrcemailrenderer/templates/onlinepaymentservice/OnlinePaymentServiceTemplates.scala

PAS-1158: From email address change

PAS-1158: From email address change

---

app/preview/TemplateParams.scala
app/uk/gov/hmrc/hmrcemailrenderer/templates/onlinepaymentservice/passengers_confirmation.scala.html
app/uk/gov/hmrc/hmrcemailrenderer/templates/onlinepaymentservice/passengers_confirmation.scala.txt

PAS-1208: Content updates for passenger email
TSR-https://jira.tools.tax.service.gov.uk/browse/DC-3199
Passenger ticket: https://jira.tools.tax.service.gov.uk/browse/PAS-1208

PAS-1208: Content updates for passenger email

---

app/preview/TemplateParams.scala
app/uk/gov/hmrc/hmrcemailrenderer/templates/onlinepaymentservice/passengers_confirmation.scala.html
app/uk/gov/hmrc/hmrcemailrenderer/templates/onlinepaymentservice/passengers_confirmation.scala.txt

PAS-1231 : Update EU-GB Email to Include Produced in/Evidence Fields.
This changes must go to production on or after 15th of March 2021. 
PR Link for Passengers Declaration Service :  https://github.com/hmrc/bc-passengers-declarations/pull/72

PAS-1231 : Update EU-GB Email to Include Produced in/Evidence Fields

---

app/uk/gov/hmrc/hmrcemailrenderer/templates/api/ApiTemplates.scala
app/uk/gov/hmrc/hmrcemailrenderer/templates/api/apiApplicationRejectedNotification.scala.html
app/uk/gov/hmrc/hmrcemailrenderer/templates/api/apiApplicationRejectedNotification.scala.txt
test/uk/gov/hmrc/hmrcemailrenderer/templates/api/ApiTemplatesSpec.scala

Following review of changes (see DC-3241) some changes.

APIS-5193 - Changes to Application Check Failed template

---

app/preview/TemplateParams.scala
app/uk/gov/hmrc/hmrcemailrenderer/templates/onlinepaymentservice/passengers_confirmation.scala.html

PAS-1180 : Defect fix of the alignment issue for passenger amendment change.

PAS-1180 : Defect fix for the alignment issue passenger amendment change

---

app/preview/TemplateParams.scala
app/uk/gov/hmrc/hmrcemailrenderer/templates/ServiceIdentifier.scala
app/uk/gov/hmrc/hmrcemailrenderer/templates/TemplateLocator.scala
app/uk/gov/hmrc/hmrcemailrenderer/templates/aeo/AEOMRATemplates.scala
app/uk/gov/hmrc/hmrcemailrenderer/templates/aeo/ReportFormatter.scala
app/uk/gov/hmrc/hmrcemailrenderer/templates/aeo/aeoMraRowDataExchangeReport.scala.html
app/uk/gov/hmrc/hmrcemailrenderer/templates/aeo/aeoMraRowDataExchangeReport.scala.txt
test/uk/gov/hmrc/hmrcemailrenderer/templates/TemplateLocatorSpec.scala

Hello, I created this template as tool for us (AEO MRA team) to receive regular scheduled updates about a job that we want to monitor.
Here is the template:

AEOM 152 email status reports

---

app/uk/gov/hmrc/hmrcemailrenderer/templates/onlinepaymentservice/open_banking_payment_successful.scala.html
app/uk/gov/hmrc/hmrcemailrenderer/templates/onlinepaymentservice/open_banking_payment_successful_cy.scala.html

ET-OPS-6288 Alter receipt email for Open Banking payments

---

app/uk/gov/hmrc/hmrcemailrenderer/templates/onlinepaymentservice/passengers_confirmation.scala.html
app/uk/gov/hmrc/hmrcemailrenderer/templates/onlinepaymentservice/passengers_confirmation.scala.txt

Stop Showing N/A in Service. N/A has to be replaced by Unknown

[PAS-1323] : Stop Showing N/A in Service

---

app/preview/TemplateParams.scala
app/uk/gov/hmrc/hmrcemailrenderer/templates/pods/PodsTemplates.scala
app/uk/gov/hmrc/hmrcemailrenderer/templates/pods/schemeMigrationConfirmation.scala.html
app/uk/gov/hmrc/hmrcemailrenderer/templates/pods/schemeMigrationConfirmation.scala.txt
test/uk/gov/hmrc/hmrcemailrenderer/templates/TemplateLocatorSpec.scala

PODS-5800 : PODS Scheme Migration Confirmation Email

PODS-5800 : PODS Scheme Migration Confirmation Email

---

app/uk/gov/hmrc/hmrcemailrenderer/templates/pods/pspRegistered.scala.html
app/uk/gov/hmrc/hmrcemailrenderer/templates/pods/pspRegistered.scala.txt

PODS-5981 : Update the Practitioner spelling in the PSP confirmation email

PODS-5981 : Update the Practitioner spelling in the PSP confirmation email

---

app/uk/gov/hmrc/hmrcemailrenderer/templates/ats/annualTaxSummariesMessageAlert.scala.html
app/uk/gov/hmrc/hmrcemailrenderer/templates/ats/annualTaxSummariesMessageAlert.scala.txt
app/uk/gov/hmrc/hmrcemailrenderer/templates/ats/annualTaxSummariesMessageAlert_cy.scala.html
app/uk/gov/hmrc/hmrcemailrenderer/templates/ats/annualTaxSummariesMessageAlert_cy.scala.txt
test/uk/gov/hmrc/hmrcemailrenderer/templates/AtsTemplates/AtsAnnualTaxReturnWelshSpec.scala

Reverts hmrc/hmrc-email-renderer#833

Revert "DC-3896 - updates to ATS email template"

---

app/uk/gov/hmrc/hmrcemailrenderer/templates/paye/newTaxEstimateMessageAlert.scala.html
app/uk/gov/hmrc/hmrcemailrenderer/templates/paye/newTaxEstimateMessageAlert.scala.txt
app/uk/gov/hmrc/hmrcemailrenderer/templates/paye/taxEstimateMessageAlert_cy.scala.html
app/uk/gov/hmrc/hmrcemailrenderer/templates/paye/taxEstimateMessageAlert_cy.scala.txt
test/uk/gov/hmrc/hmrcemailrenderer/templates/paye/TaxEstimateMessageAlertWelshSpec.scala

Reverts hmrc/hmrc-email-renderer#837

Revert "Revert the content change for P2 email needed from 1st Feb"

---

app/uk/gov/hmrc/hmrcemailrenderer/templates/ats/annualTaxSummariesMessageAlert.scala.html
app/uk/gov/hmrc/hmrcemailrenderer/templates/ats/annualTaxSummariesMessageAlert.scala.txt
app/uk/gov/hmrc/hmrcemailrenderer/templates/ats/annualTaxSummariesMessageAlert_cy.scala.html
app/uk/gov/hmrc/hmrcemailrenderer/templates/ats/annualTaxSummariesMessageAlert_cy.scala.txt
test/uk/gov/hmrc/hmrcemailrenderer/templates/AtsTemplates/AtsAnnualTaxReturnWelshSpec.scala

This reverts commit 176ce209cc1c9896e90e55286799b8ca60d4f761.

Revert "Revert "updates to ATS email template (#833)" (#844)"

---

app/preview/TemplateParams.scala
app/uk/gov/hmrc/hmrcemailrenderer/templates/TemplateLocator.scala
app/uk/gov/hmrc/hmrcemailrenderer/templates/rald/RaldTemplates.scala
app/uk/gov/hmrc/hmrcemailrenderer/templates/rald/rald_connection_removed.scala.html
app/uk/gov/hmrc/hmrcemailrenderer/templates/rald/rald_connection_removed.scala.txt
app/uk/gov/hmrc/hmrcemailrenderer/templates/rald/rald_connection_removed_cy.scala.html
app/uk/gov/hmrc/hmrcemailrenderer/templates/rald/rald_connection_removed_cy.scala.txt
test/uk/gov/hmrc/hmrcemailrenderer/templates/TemplateLocatorSpec.scala
test/uk/gov/hmrc/hmrcemailrenderer/templates/rald/RaldConnectionRemovedCySpec.scala
test/uk/gov/hmrc/hmrcemailrenderer/templates/rald/RaldConnectionRemovedSpec.scala

new email templates:
- rald_connection_removed
- rald_connection_removed_cy

DC-4029 VOA-3222 RALD Email templates rald_connection_removed (en/cy)

---

app/preview/TemplateParams.scala

DC-4029 scalastyle fix

---

app/uk/gov/hmrc/hmrcemailrenderer/templates/euSubsidy/removedAsLeadEmailToPreviousLead.scala.html
app/uk/gov/hmrc/hmrcemailrenderer/templates/euSubsidy/removedAsLeadEmailToPreviousLead.scala.txt

ticket details -> https://jira.tools.tax.service.gov.uk/browse/ESC-416

EC-417 change content

---

app/uk/gov/hmrc/hmrcemailrenderer/templates/mdr/mdrFileUploadSuccessful.scala.html
app/uk/gov/hmrc/hmrcemailrenderer/templates/mdr/mdrFileUploadSuccessful.scala.txt
app/uk/gov/hmrc/hmrcemailrenderer/templates/mdr/mdrFileUploadUnsuccessful.scala.html
app/uk/gov/hmrc/hmrcemailrenderer/templates/mdr/mdrFileUploadUnsuccessful.scala.txt

Minor content changes to MDR success and failure templates

DAC6-1468-2 | Minor content changes

---

CONTRIBUTING.md

Replaced Dominic Warren as a ticket reviewer for email template changes

Updated COntibuting.md

---

app/preview/TemplateParams.scala
app/uk/gov/hmrc/hmrcemailrenderer/templates/euSubsidy/createUndertakingEmailToLead.scala.html
app/uk/gov/hmrc/hmrcemailrenderer/templates/euSubsidy/createUndertakingEmailToLead.scala.txt
app/uk/gov/hmrc/hmrcemailrenderer/templates/euSubsidy/disabledUndertakingEmailToBE.scala.html
app/uk/gov/hmrc/hmrcemailrenderer/templates/euSubsidy/disabledUndertakingEmailToBE.scala.txt
app/uk/gov/hmrc/hmrcemailrenderer/templates/euSubsidy/disabledUndertakingEmailToLead.scala.html
app/uk/gov/hmrc/hmrcemailrenderer/templates/euSubsidy/disabledUndertakingEmailToLead.scala.txt
app/uk/gov/hmrc/hmrcemailrenderer/templates/euSubsidy/memberRemoveThemselfEmailToBE.scala.html
app/uk/gov/hmrc/hmrcemailrenderer/templates/euSubsidy/memberRemoveThemselfEmailToBE.scala.txt
app/uk/gov/hmrc/hmrcemailrenderer/templates/euSubsidy/memberRemoveThemselfEmailToLead.scala.html
app/uk/gov/hmrc/hmrcemailrenderer/templates/euSubsidy/memberRemoveThemselfEmailToLead.scala.txt
app/uk/gov/hmrc/hmrcemailrenderer/templates/euSubsidy/promotedOtherAsLeadEmailToBE.scala.html
app/uk/gov/hmrc/hmrcemailrenderer/templates/euSubsidy/promotedOtherAsLeadEmailToBE.scala.txt
app/uk/gov/hmrc/hmrcemailrenderer/templates/euSubsidy/promotedOtherAsLeadEmailToLead.scala.html
app/uk/gov/hmrc/hmrcemailrenderer/templates/euSubsidy/promotedOtherAsLeadEmailToLead.scala.txt
app/uk/gov/hmrc/hmrcemailrenderer/templates/euSubsidy/promotedThemselfAsLeadEmailToLead.scala.html
app/uk/gov/hmrc/hmrcemailrenderer/templates/euSubsidy/promotedThemselfAsLeadEmailToLead.scala.txt
app/uk/gov/hmrc/hmrcemailrenderer/templates/euSubsidy/removedAsLeadEmailToPreviousLead.scala.html
app/uk/gov/hmrc/hmrcemailrenderer/templates/euSubsidy/removedAsLeadEmailToPreviousLead.scala.txt
app/uk/gov/hmrc/hmrcemailrenderer/templates/euSubsidy/undertakingMemberAddedEmailToBE.scala.html
app/uk/gov/hmrc/hmrcemailrenderer/templates/euSubsidy/undertakingMemberAddedEmailToBE.scala.txt
app/uk/gov/hmrc/hmrcemailrenderer/templates/euSubsidy/undertakingMemberAddedEmailToLead.scala.html
app/uk/gov/hmrc/hmrcemailrenderer/templates/euSubsidy/undertakingMemberAddedEmailToLead.scala.txt
app/uk/gov/hmrc/hmrcemailrenderer/templates/euSubsidy/undertakingMemberRemovedEmailToBE.scala.html
app/uk/gov/hmrc/hmrcemailrenderer/templates/euSubsidy/undertakingMemberRemovedEmailToBE.scala.txt
app/uk/gov/hmrc/hmrcemailrenderer/templates/euSubsidy/undertakingMemberRemovedEmailToLead.scala.html
app/uk/gov/hmrc/hmrcemailrenderer/templates/euSubsidy/undertakingMemberRemovedEmailToLead.scala.txt

ticket details -> https://jira.tools.tax.service.gov.uk/browse/ESC-602

ESC-602 email template update

---

app/uk/gov/hmrc/hmrcemailrenderer/templates/onlinepaymentservice/OnlinePaymentServiceTemplates.scala
app/uk/gov/hmrc/hmrcemailrenderer/templates/onlinepaymentservice/SddsTemplateParameters.scala

[KN][OPS-8232] changing default code to generalize email nudges

---

app/uk/gov/hmrc/hmrcemailrenderer/templates/onlinepaymentservice/sdds_ddi_unpaid_dcs_alert.scala.html
app/uk/gov/hmrc/hmrcemailrenderer/templates/onlinepaymentservice/sdds_ddi_unpaid_dcs_alert.scala.txt

[KN][OPS-8088] Email nudges wash up ticket

---

app/uk/gov/hmrc/hmrcemailrenderer/templates/euSubsidy/createUndertakingEmailToLead.scala.html
app/uk/gov/hmrc/hmrcemailrenderer/templates/euSubsidy/createUndertakingEmailToLead.scala.txt
app/uk/gov/hmrc/hmrcemailrenderer/templates/euSubsidy/disabledUndertakingEmailToBE.scala.html
app/uk/gov/hmrc/hmrcemailrenderer/templates/euSubsidy/disabledUndertakingEmailToBE.scala.txt
app/uk/gov/hmrc/hmrcemailrenderer/templates/euSubsidy/disabledUndertakingEmailToLead.scala.html
app/uk/gov/hmrc/hmrcemailrenderer/templates/euSubsidy/disabledUndertakingEmailToLead.scala.txt
app/uk/gov/hmrc/hmrcemailrenderer/templates/euSubsidy/memberRemoveThemselfEmailToBE.scala.html
app/uk/gov/hmrc/hmrcemailrenderer/templates/euSubsidy/memberRemoveThemselfEmailToBE.scala.txt
app/uk/gov/hmrc/hmrcemailrenderer/templates/euSubsidy/memberRemoveThemselfEmailToLead.scala.html
app/uk/gov/hmrc/hmrcemailrenderer/templates/euSubsidy/memberRemoveThemselfEmailToLead.scala.txt
app/uk/gov/hmrc/hmrcemailrenderer/templates/euSubsidy/promotedOtherAsLeadEmailToBE.scala.html
app/uk/gov/hmrc/hmrcemailrenderer/templates/euSubsidy/promotedOtherAsLeadEmailToBE.scala.txt
app/uk/gov/hmrc/hmrcemailrenderer/templates/euSubsidy/promotedOtherAsLeadEmailToLead.scala.html
app/uk/gov/hmrc/hmrcemailrenderer/templates/euSubsidy/promotedOtherAsLeadEmailToLead.scala.txt
app/uk/gov/hmrc/hmrcemailrenderer/templates/euSubsidy/promotedThemselfAsLeadEmailToLead.scala.html
app/uk/gov/hmrc/hmrcemailrenderer/templates/euSubsidy/promotedThemselfAsLeadEmailToLead.scala.txt
app/uk/gov/hmrc/hmrcemailrenderer/templates/euSubsidy/removedAsLeadEmailToPreviousLead.scala.html
app/uk/gov/hmrc/hmrcemailrenderer/templates/euSubsidy/removedAsLeadEmailToPreviousLead.scala.txt
app/uk/gov/hmrc/hmrcemailrenderer/templates/euSubsidy/undertakingMemberAddedEmailToBE.scala.html
app/uk/gov/hmrc/hmrcemailrenderer/templates/euSubsidy/undertakingMemberAddedEmailToBE.scala.txt
app/uk/gov/hmrc/hmrcemailrenderer/templates/euSubsidy/undertakingMemberAddedEmailToLead.scala.html
app/uk/gov/hmrc/hmrcemailrenderer/templates/euSubsidy/undertakingMemberAddedEmailToLead.scala.txt
app/uk/gov/hmrc/hmrcemailrenderer/templates/euSubsidy/undertakingMemberRemovedEmailToBE.scala.html
app/uk/gov/hmrc/hmrcemailrenderer/templates/euSubsidy/undertakingMemberRemovedEmailToBE.scala.txt
app/uk/gov/hmrc/hmrcemailrenderer/templates/euSubsidy/undertakingMemberRemovedEmailToLead.scala.html
app/uk/gov/hmrc/hmrcemailrenderer/templates/euSubsidy/undertakingMemberRemovedEmailToLead.scala.txt

Summary of changes
* following a change in the name of the EU Subsidy Compliance service, all email templates have been updated to reflect the new service name of `Report and manage your allowancefor Customs Duty waiver claims`

DC-4415 update service name in eu-subsidy emails

---

app/preview/TemplateParams.scala
app/uk/gov/hmrc/hmrcemailrenderer/templates/agent/AgentTemplates.scala
app/uk/gov/hmrc/hmrcemailrenderer/templates/agent/agent_permissions_all_failed.scala.html
app/uk/gov/hmrc/hmrcemailrenderer/templates/agent/agent_permissions_all_failed.scala.txt
app/uk/gov/hmrc/hmrcemailrenderer/templates/agent/agent_permissions_all_failed_cy.scala.html
app/uk/gov/hmrc/hmrcemailrenderer/templates/agent/agent_permissions_all_failed_cy.scala.txt
app/uk/gov/hmrc/hmrcemailrenderer/templates/agent/agent_permissions_some_failed.scala.html
app/uk/gov/hmrc/hmrcemailrenderer/templates/agent/agent_permissions_some_failed.scala.txt
app/uk/gov/hmrc/hmrcemailrenderer/templates/agent/agent_permissions_some_failed_cy.scala.html
app/uk/gov/hmrc/hmrcemailrenderer/templates/agent/agent_permissions_some_failed_cy.scala.txt
app/uk/gov/hmrc/hmrcemailrenderer/templates/agent/agent_permissions_success.scala.html
app/uk/gov/hmrc/hmrcemailrenderer/templates/agent/agent_permissions_success.scala.txt
app/uk/gov/hmrc/hmrcemailrenderer/templates/agent/agent_permissions_success_cy.scala.html
app/uk/gov/hmrc/hmrcemailrenderer/templates/agent/agent_permissions_success_cy.scala.txt
test/uk/gov/hmrc/hmrcemailrenderer/templates/TemplateLocatorSpec.scala

APB-6007 [CS] add agent_permissions templates

---

app/uk/gov/hmrc/hmrcemailrenderer/templates/onlinepaymentservice/recon_surcharge_report.scala.html

Signed-off-by: Pawel Panasewicz <2970040+pawelpanasewicz@users.noreply.github.com>

[PP][OPS-8050] reorder tables on the surcharge recon report

---

app/preview/TemplateParams.scala
app/uk/gov/hmrc/hmrcemailrenderer/templates/pods/PodsTemplates.scala
app/uk/gov/hmrc/hmrcemailrenderer/templates/pods/userResearchBanner.scala.html
app/uk/gov/hmrc/hmrcemailrenderer/templates/pods/userResearchBanner.scala.txt
test/uk/gov/hmrc/hmrcemailrenderer/templates/TemplateLocatorSpec.scala

Email template for PODS team user-research banner

PODS-7852b New UR Template

---

app/preview/TemplateParams.scala
app/uk/gov/hmrc/hmrcemailrenderer/templates/cbcrnew/CBCRNewTemplates.scala
app/uk/gov/hmrc/hmrcemailrenderer/templates/cbcrnew/cbcAgentFileUploadSuccessful.scala.html
app/uk/gov/hmrc/hmrcemailrenderer/templates/cbcrnew/cbcAgentFileUploadSuccessful.scala.txt
app/uk/gov/hmrc/hmrcemailrenderer/templates/cbcrnew/cbcAgentFileUploadUnsuccessful.scala.html
app/uk/gov/hmrc/hmrcemailrenderer/templates/cbcrnew/cbcAgentFileUploadUnsuccessful.scala.txt
app/uk/gov/hmrc/hmrcemailrenderer/templates/cbcrnew/cbcFileUploadSuccessful.scala.html
app/uk/gov/hmrc/hmrcemailrenderer/templates/cbcrnew/cbcFileUploadSuccessful.scala.txt
app/uk/gov/hmrc/hmrcemailrenderer/templates/cbcrnew/cbcFileUploadUnsuccessful.scala.html
app/uk/gov/hmrc/hmrcemailrenderer/templates/cbcrnew/cbcFileUploadUnsuccessful.scala.txt
app/uk/gov/hmrc/hmrcemailrenderer/templates/cbcrnew/forClientTradingName.scala.html

This PR:
- Updates the country-by-country (CBC) file upload templates

DAC6-2554: Update CBC file upload templates

---

app/preview/TemplateParams.scala
app/preview/examples/GG.scala
app/uk/gov/hmrc/hmrcemailrenderer/templates/gg/EmailVerificationPasscode.scala.html
app/uk/gov/hmrc/hmrcemailrenderer/templates/gg/EmailVerificationPasscode.scala.txt
app/uk/gov/hmrc/hmrcemailrenderer/templates/gg/EmailVerificationPasscodeWelsh.scala.html
app/uk/gov/hmrc/hmrcemailrenderer/templates/gg/EmailVerificationPasscodeWelsh.scala.txt

using team specific example class as scala compiler was struggling to parse TemplateParams because of the excessive number of lines

GG-6869 add page_title param to GG email_verification template

---

app/preview/TemplateParams.scala
app/uk/gov/hmrc/hmrcemailrenderer/templates/agent/AgentTemplates.scala
app/uk/gov/hmrc/hmrcemailrenderer/templates/agent/suspended_contact_details.scala.html
app/uk/gov/hmrc/hmrcemailrenderer/templates/agent/suspended_contact_details.scala.txt
test/uk/gov/hmrc/hmrcemailrenderer/templates/TemplateLocatorSpec.scala

APB-6759 [RW] add template for suspended agent

APB-6759 [RW] add template for suspended agent

---

app/uk/gov/hmrc/hmrcemailrenderer/templates/onlinepaymentservice/cds_ddi_setup_dcs_alert.scala.html
app/uk/gov/hmrc/hmrcemailrenderer/templates/onlinepaymentservice/cds_ddi_setup_dcs_alert.scala.txt

This reverts commit 85b241181a2ccb0c09daf6c5fe794ad2bcaf79c2.

Revert "[AC][OPS-10457] update DD setup alert message for CDS (#1115)"

---

app/uk/gov/hmrc/hmrcemailrenderer/templates/paye/newTaxEstimateMessageAlert.scala.html
app/uk/gov/hmrc/hmrcemailrenderer/templates/paye/newTaxEstimateMessageAlert.scala.txt
app/uk/gov/hmrc/hmrcemailrenderer/templates/paye/taxEstimateMessageAlert_cy.scala.html
app/uk/gov/hmrc/hmrcemailrenderer/templates/paye/taxEstimateMessageAlert_cy.scala.txt

This reverts commit f18f9c6210bb50ce1de409b6f26b71096051438c.

Revert "DC-5684 - Amend the tax year of the P2 Nudge email (#1120)"

---

app/preview/TemplateParams.scala
app/uk/gov/hmrc/hmrcemailrenderer/templates/hipp/HippTemplates.scala
app/uk/gov/hmrc/hmrcemailrenderer/templates/hipp/RemoveMemberFromTeam.scala.html
app/uk/gov/hmrc/hmrcemailrenderer/templates/hipp/RemoveMemberFromTeam.scala.txt
test/uk/gov/hmrc/hmrcemailrenderer/templates/TemplateLocatorSpec.scala

HIPP-1378: Add HIPP user removed from team email template

---

app/preview/TemplateParams.scala
app/uk/gov/hmrc/hmrcemailrenderer/templates/ServiceIdentifier.scala
app/uk/gov/hmrc/hmrcemailrenderer/templates/TemplateLocator.scala
app/uk/gov/hmrc/hmrcemailrenderer/templates/tgp/DownloadRecordNotification.scala.html
app/uk/gov/hmrc/hmrcemailrenderer/templates/tgp/DownloadRecordNotification.scala.txt
app/uk/gov/hmrc/hmrcemailrenderer/templates/tgp/DownloadRecordNotification_cy.scala.html
app/uk/gov/hmrc/hmrcemailrenderer/templates/tgp/DownloadRecordNotification_cy.scala.txt
app/uk/gov/hmrc/hmrcemailrenderer/templates/tgp/TgpTemplates.scala
test/uk/gov/hmrc/hmrcemailrenderer/templates/TemplateLocatorSpec.scala

DC-6712 Trader Goods Profile Email notification on file available to download

DC-6712 Trader Goods Profile Email notification on file available to download

---

app/uk/gov/hmrc/hmrcemailrenderer/templates/ats/AtsTemplates.scala
test/uk/gov/hmrc/hmrcemailrenderer/templates/AtsTemplates/AtsAnnualTaxReturnWelshSpec.scala

Reverts hmrc/hmrc-email-renderer#1189

Revert "DC-6672 Update tax year in email subject line for SA-ATS email template."

---

app/uk/gov/hmrc/hmrcemailrenderer/templates/digitalcontact/newMessageAlert_VRT1214A.scala.html
app/uk/gov/hmrc/hmrcemailrenderer/templates/digitalcontact/newMessageAlert_VRT1214A.scala.txt
app/uk/gov/hmrc/hmrcemailrenderer/templates/digitalcontact/newMessageAlert_VRT1214C.scala.html
app/uk/gov/hmrc/hmrcemailrenderer/templates/digitalcontact/newMessageAlert_VRT1214C.scala.txt

ticket: [DL-13563](https://jira.tools.tax.service.gov.uk/browse/DL-13563)

change content for VRT1214A and VRT1214C

---

app/preview/TemplateParams.scala
app/uk/gov/hmrc/hmrcemailrenderer/templates/hipp/HippTemplates.scala
app/uk/gov/hmrc/hmrcemailrenderer/templates/hipp/NewProductionAccessRequest.scala.html
app/uk/gov/hmrc/hmrcemailrenderer/templates/hipp/NewProductionAccessRequest.scala.txt
app/uk/gov/hmrc/hmrcemailrenderer/templates/hipp/ProductionAccessRequestApproved.scala.html
app/uk/gov/hmrc/hmrcemailrenderer/templates/hipp/ProductionAccessRequestApproved.scala.txt
app/uk/gov/hmrc/hmrcemailrenderer/templates/hipp/ProductionAccessRequestRejected.scala.html
app/uk/gov/hmrc/hmrcemailrenderer/templates/hipp/ProductionAccessRequestRejected.scala.txt
app/uk/gov/hmrc/hmrcemailrenderer/templates/hipp/ProductionAccessRequestSubmitted.scala.html
app/uk/gov/hmrc/hmrcemailrenderer/templates/hipp/ProductionAccessRequestSubmitted.scala.txt

https://jira.tools.tax.service.gov.uk/browse/HIPP-2043

HIPP-2043: Parameterise Email content with environment
